using System;

namespace RESTFulSocial.Core.DTOs
{
    public class PostDto
    {
        /// <summary>
        /// Autogeneratedd id for post entity
        /// </summary>
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime? Date { get; set; }
        
        //[Required]
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
